[package]
name = "image-editor"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.36", features = ["derive"] }
image = {version = "0.25.6", features = ["jpeg", "png", "bmp", "ico"]}
reqwest = { version = "0.11", features = ["blocking"] }
thiserror = "1.0"
url = "2"